# Site
title:              Robotism
bio:                'A platform to document my robotics learnings.'
description:        "A platform to document my robotics learnings."
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robotism.me" # the base hostname & protocol for your site
tagline: "Notes From My Robotics Learning Quests"

# Comments
disqus_shortname:   robotically

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
linkedin:           in/sreejith-pillai-2628b6155
github:             4lhc
researchgate:       Sreejith_S_Pillai2

# personal
location:           KL, IN
phone:              000-000-0000
email:              info@default.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
